# Generated by Django 2.2.3 on 2019-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx_api_ocr_invoking', '0002_jsonocrinputmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonocrinputmodel',
            name='x_coordinates',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jsonocrinputmodel',
            name='y_coordinates',
            field=models.TextField(default='', max_length=20),
        ),
    ]
