# Generated by Django 2.2.3 on 2019-08-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJsonReturnValueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocrJson', models.CharField(max_length=3000)),
            ],
        ),
    ]
